### ISSUE TITLE
No Peers Connected

### ISSUE THREAD

**Issue by risturiz** [greenaddress/GreenBits#71] opened 2016-06-01 00:09 UTC
Hi, im having problems with GreenBits ( I think last update )... Any way to debug this?... Now the app always is offline.

Thanks.

**Comment by instagibbs** [comment] 2016-06-01 00:50
Is the app offline, or just spv peers?

**Comment by risturiz** [comment] 2016-06-01 23:54
Hi, actually in Network Monitor have "No Peers Connected"... When the app open i cant see the transacction list, only the "bits" and some links to "start use bitcoin, where buy bitcoin, etc"

**Comment by greenaddress** [comment] 2016-06-02 00:02
I don't think the SPV kicks in until you have at least one transaction to be verified

**Comment by risturiz** [comment] 2016-06-02 00:32
I have the app "Greenbits" working for months with multiple transaction without any problem... With the last update im having this "connection" problem... I dont have any personal peer selected and yes i had reset the SPV in settings... Im gona reset again.

**Comment by greenaddress** [comment] 2016-06-02 00:38
Oh, I didn't realise you had an account with transactions.

Do you see the problem both on wifi and mobile? If you want to try to debug it you could try to run adb logcat with your android phone in developer mode and see if there's any related exception being thrown or relevant logging

**Comment by risturiz** [comment] 2016-06-02 01:04
Yes (wifi and mobile)... Now i have reinstalled the app and have the same problem... I get the total of bits in real time, but any transaction... On web all is fine.

P.D. Do you have any SPV peer to insert in the list?

**Comment by greenaddress** [comment] 2016-06-02 01:22
I'm not sure the transaction list and SPV are related issues though.

Did you create a subaccount/subwallet? Did you select that in GreenBits?

**Comment by risturiz** [comment] 2016-06-02 01:35
Really strange... I downloaded anterior version and dont work either... I dont have subaccount/subwallet... The Greenaddress main app works normal (only its slow), but greenbits now have this issue... Im goin ask a friend that have same app, maybe he can help with this.

Thanks.

**Comment by greenaddress** [comment] 2016-06-02 02:25
Can you share with us the device model and the android version?

**Comment by risturiz** [comment] 2016-06-02 11:44
Moto G 2nd / Android 6.0

**Comment by jgriffiths** [comment] 2016-09-24 00:27
Hi @risturiz,

We identified an issue with SPV sync which could cause it to stall when initialising SPV which would prevent syncing from working. This issue is fixed in the latest version available from fdroid and play.

> P.D. In the app i have the connection icon appear sometimes like i was disconnected

It its possible for you to try the newest version of the app with a more reliable network connection? It would be good to determine if the issue is caused by the network intermittently dropping or by the SPV bug we fixed.

**Comment by 5chdn** [comment] 2017-01-02 18:22
Not sure if it's related, but each time I launch the app and enter my PIN, I get 

> Not connected, connection will resume automatically.

I'm somehow unable to access my funds in the app.

**Comment by greenaddress** [comment] 2017-04-26 15:38
Closing. Issue should be fixed; if not feel free to reopen

**Closed by greenaddress** 2017-04-26 15:38 UTC

**Comment by 5chdn** [comment] 2017-04-27 06:24
Yes it is. Thanks.
