### ISSUE TITLE
Crash on opening camera if clicking back - Tested on v1.54/v1.55

### ISSUE THREAD

**Issue by HostFat** [greenaddress/GreenBits#47] opened 2015-11-11 17:00 UTC
If you click the back button while the screen is still in black (you have to be fast), the app will crash.
It happens with both sweep and send functions of the camera.

Nexus 4.

**Comment by greenaddress** [comment] 2015-11-11 17:16
Android version used by @HostFat is 5.0.1

**Comment by greenaddress** [comment] 2015-11-13 13:58
For now I can't reproduce on a Nexus 5 nor on the emulator.

**Comment by instagibbs** [comment] 2015-11-13 14:02
Can't reproduce on Nexus 5X(6.0), Nexus 6(5.1) or emulators.

**Comment by greenaddress** [comment] 2015-11-17 15:15
thanks @HostFat for the debug logs - fixed in 1c330ca

**Closed by greenaddress** 2015-11-17 15:15 UTC
Labels: bug
