### ISSUE TITLE
Some issues with Greenbits 1.89

### ISSUE THREAD

**Issue by bitcoinuser** [greenaddress/GreenBits#138] opened 2016-09-24 19:28 UTC
Hi,

Since Blockstream bought Greenbits wallet, I decided to put my bitcoins on it. But I'm experiencing some problems:
1- Many times when I insert PIN to login, Greenbits crash.
2- Today when I logged, something very stranged happened:
* The bitcoins balance showed NOT on the correct account.
* Then showed duplicated on two of my accounts
* When I selected the account with bitcoin, I didn't see transfers history.
Obs. All showed correctly after I restart the app.

![screenshot_2016-09-24-16-10-35](https://cloud.githubusercontent.com/assets/1178856/18810726/d920caf8-8273-11e6-9046-b2b8fc92b825.png)

![screenshot_2016-09-24-16-09-31](https://cloud.githubusercontent.com/assets/1178856/18810728/df1bb706-8273-11e6-9e02-7ea4334b5c19.png)

![screenshot_2016-09-24-16-09-19](https://cloud.githubusercontent.com/assets/1178856/18810729/e671b7da-8273-11e6-84d6-2ee4ade2aa64.png)

**Comment by bitcoinuser** [comment] 2016-09-24 19:30
And with all this cracy things, I could generate receiving address. But I couldn't know if the address generated was for the correct account.

**Comment by greenaddress** [comment] 2016-09-24 19:31
Hi, apologises for the bug you have hit.

We have encountered some instances of the same bugs and have fixed some already and are working on the remaining ones. We should issue an update very soon that reflect this.

A work around seems to be going to the receive tab when the activity tab is not refreshed properly (generally it happens when changed within the send tab). Let me know if you can reproduce it in other circumstances too.

Thanks!

**Comment by bitcoinuser** [comment] 2016-09-24 20:18
Google Play Store.

**Comment by greenaddress** [comment] 2016-09-24 22:50
@bitcoinuser can you let us know the device model? did you report the crash to the store when the app crashed and you got a prompt?

If you know how it would also be nice to get an adb logcat when you have a PIN crash. This is to make sure we have already fixed it or fix this new instance.

Thanks

**Comment by bitcoinuser** [comment] 2016-09-24 22:56
@greenaddress The device is LG-D805.
Yes I reported the crash to store when the app crashed.
I don't know how to get an adb logcat. If is easy, I can try.

Thanks

**Comment by greenaddress** [comment] 2016-09-24 23:07
Ok that crash is fixed in master. We'll fix the other issues and release a new version. Thanks for the help. 

For getting the adb logcat (useful anyway for any issue in the future for faster fixes) I can provide more specific instructions depending on what operating system you use, one of the easiest way is probably to install https://developer.android.com/studio/install.html and then look up the android monitor on the bottom with the device connected via USB and with USB debugging enabled (which requires developed mode enabled https://developer.android.com/studio/run/device.html) 

If you have a linux distro there may be some adb available in a distro repo or on osx under brew.

Using adb can be easy if you are handy with command line and/or navigating android menus but don't worry if you can't be bothered or find it difficult, it can be a hairy process and feel free to ask questions.

**Comment by bitcoinuser** [comment] 2016-10-04 16:02
> Ok that PIN crash is already fixed in master. We'll fix the other issues and release a new version. Thanks for the help.

I updated to version 1.90 and sometimes, before insert the PIN, Greenbits crash. I reported the crash to the store when the app crashed. Happened two times.

Thanks.

**Comment by greenaddress** [comment] 2016-10-04 16:36
Got the reports, sorry for it being still around and working on it, thanks

**Comment by greenaddress** [comment] 2016-10-06 11:59
@bitcoinuser we have release r1.91, we think it fixes your issue.

The app will take at least an hour or so to be available via Play and it should take a couple of days for F-Droid to pick up. Otherwise if you just want the apk it is available from the release [page](https://github.com/greenaddress/GreenBits/releases/tag/r1.91)

**Comment by bitcoinuser** [comment] 2016-10-06 14:21
Hi @greenaddress. I'm not experiencing the bug anymore with version 1.91. 

Thanks

**Comment by jgriffiths** [comment] 2016-10-07 04:02
Thanks for reporting back @bitcoinuser, closing this issue now.

**Closed by jgriffiths** 2016-10-07 04:02 UTC
