### ISSUE TITLE
SPV not synching

### ISSUE THREAD

**Issue by gabridome** [greenaddress/GreenBits#59] opened 2016-04-13 05:17 UTC
Even if the blocks seem to be downloaded (0 blocks left) the question mark next to the balance remain.
I tried twice to reset the SPV but the app crashes.
There is a strange message: "Downloading chain from trusted peer: com.google.util.concurrent.SettableFuture@21ee59f." and the writings in the end changes continuously.

**Comment by greenaddress** [comment] 2016-04-13 10:31
Hi

Thanks for the bug report.

The trusted peer msg is a bug that has been fixed yesterday and has been in since Feb https://github.com/greenaddress/GreenBits/commit/2dcd619e19df490e72745fd47c1e74f5903463d5 (now with the fix it shows correctly the ip:port, it hasn't been released yet, will be in 1.77 though)

I can't however reproduce the crash and I can't see in Play any error report for version 1.76 nor any issue in the last two days for any other version that could be related to this.

Can you try to reproduce it while connected via usb to a computer with adb/android studio installed so we can get the logs? 

From command line do 

`adb logcat`

In android studio you should see it in the log console

**Closed** 2016-04-13 13:29 UTC
